import type { Metadata } from "next"
import ClientRootLayout from "./ClientRootLayout"

export const metadata: Metadata = {
  title: "Shopper",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  )
}
